- name: install GC3Pie
  get_url:
    url: {{ gc3pie_install_script }}
    dest: '{{ vm_login }}'/install.py
    mode: 0750

- name: install GC3Pie in development mode
  command: python {{ vm_login }}./install.py --develop -y --no-gc3apps -a openstack

- name: Configure GC3Pie virtualenv
  lineinfile: dest={{ item.dest }} line={{ item.line }}
  with_items:
      - { dest: '$HOME/.bashrc', line: 'source $HOME/gc3pie/bin/activate' }

- name: Deploying config file
  copy: 
    src: gc3pie.conf.tmlp
    dest: $HOME/.gc3/gc3pie.conf
    owner: {{ vm_login }}
    mode: 0644

- name: checkout tp_automation repo
  git:
    repo: {{ tp_git_automation }}
    dest: {{ apps_path }}
    version: release-0.22

- name: Create log folder
  file:
    path: {{ gtp_daemon_log_dir }}
    owner: {{ vm_login }}
    become: yes

- name: start monitoring service
  - command: python {{ gtp_daemon }} -r localhost -o {{ gpt_session }} {{ data_inbox }} -vvv --working_dir {{ gtp_daemon_log_dir }}