- name: install needed packages
  - apt: status=present {{item}}
  - with_items:
// sudo pip3 install --upgrade pip
// sudo npm install -g configurable-http-proxy
// sudo pip3 install jupyterhub
// sudo pip3 install notebook
// sudo pip install daytime
// sudo pip3 install daytime
// sudo pip install encoding
// sudo pip3 install encoding
// sudo /usr/bin/python pip install virtualenvwrapper
   
- name: checkout IMC tools
  git:
    repo: '{{item.repo}}'
    dest: '{{ apps_path }}/imc/{{item.name}}'
    version: '{{item.release}}'
  loop: '{{imc-pipeline-items}}'

- name: install IMC tools
  pip:
    requirements={{ apps_path }}/imctools/requirements.txt
    executable={{ pip_exec_path }}

- name: fix ownership
  file:
    path={{ apps_path }}/imctools/
    owner={{ apps_owner }}
    group={{ apps_owner }}
    state=directory
    recurse=yes

- name: fix PYTHONPATH
  lineinfile: dest=/home/{{ apps_owner }}/.bashrc line="export PYTHONPATH={{ apps_path }}/imctools/imctools:$PYTHONPATH"

# - name: checkout IMC pipeline
#   git:
#     repo={{ imc_pipeline }}
#     dest={{ apps_path }}/imc-pipeline/
#     version={{ imc_pipeline_release }}

