---
#
# Install JupyterHub and run it on port 443
#
# Follows installation instructions at:
# - https://github.com/jupyterhub/jupyterhub/blob/master/README.md#installation
#

- name: install dependencies
  package:
    name={{ item }}
    state=present
  with_items:
    - git
    - nodejs-legacy
    - npm
    - python
    - python-dev
    - python-setuptools
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - sudo
    - apt-transport-https
    - supervisor

- name: install configurable-http-proxy
  command: npm install -g configurable-http-proxy

# - name: install JupyterHub through conda
#   command: conda install -y -c conda-forge {{ item }}
#   with_items:
#     - jupyterhub

- name: install JupyterHub with PIP
  command: /opt/Anaconda3-5.1.0-Linux-x86_64/bin/pip install --upgrade {{ item }}
  with_items:
     - notebook
     - jupyterhub
     - jupyterlab

- name: Create directories
  file:
    path: '{{item}}'
    state: directory
    mode: 0755
  with_items:
    - /etc/jupyterhub
    - /var/lib/jupyterhub

# Configuration
- name: Create secret tokens
  shell: |
    openssl rand -hex 32 | tr -d '\n' > '/var/lib/jupyterhub/{{ item }}'
  args:
    creates: '/var/lib/jupyterhub/{{ item }}'
  with_items:
    - jupyterhub_cookie_secret
    - jupyterhub_proxy_auth_token

- name: Deploy configuration file
  copy:
    dest: '/etc/jupyterhub/jupyterhub_config.py'
    src:  'etc/jupyterhub/jupyterhub_config.py'
    mode: 0400

# see: https://serialized.net/2013/04/simply-generating-self-signed-ssl-certs-with-ansible/
- name: Create self-signed SSL cert
  command: |
    openssl req -x509 -new -batch -days 3650 -subj "/O=BBLab/OU=JupyterHub/CN={{ansible_fqdn}}"  -newkey rsa:2048 -nodes -outform PEM -keyout /etc/jupyterhub/jupyterhub.key.pem -out /etc/jupyterhub/jupyterhub.crt.pem -extensions usr_cert
  args:
    creates: /etc/jupyterhub/jupyterhub.key.pem

# FIXME: should the following be reworked into an independent `supervisord` role?
- name: Manage JupyterHub with `supervisord`
  copy:
    dest: '/etc/supervisor/conf.d/jupyterhub.conf'
    src: 'etc/supervisor/conf.d/jupyterhub.conf'
    mode: 0444
  register: _deploy_supervisord_conf_for_jupyterhub

- name: Ensure supervisord is running and starts again at boot
  service:
    name: supervisor
    enabled: yes
    state: started

- name: Ensure supervisord re-reads config
  shell: |
    supervisorctl reread;
    supervisorctl update;
  when: _deploy_supervisord_conf_for_jupyterhub|changed

- name: Ensure JupyterHub has been started by supervisord
  command: |
    supervisorctl start jupyterhub

# - name: install jupyterhub init script
#   copy: src=jupyterhub-init dest=/etc/init.d/jupyterhub mode=755 owner=root group=root
#   become: yes
#   become_method: sudo
#   tags: jupyter

# - name: start jupyterhub
#   service: name=jupyterhub enabled=yes state=started
#   become: yes
#   become_method: sudo
#   tags: jupyter
