---

- name: deploy backup scripts
  git:
    repo: "https://github.com/openstack/freezer.git"
    dest: /opt/freezer
    version: stable/ocata

- name: Install freezer required packages
  package:
     name: "{{ item }}"
     state: present
  loop:
     - python-dev
     - python-pip
     - git
     - openssl
     - gcc
     - make
     - automake

- name: Install requirements with pip
  pip:
   chdir: /opt/freezer
   requirements: requirements.txt

- name: Install freezer from source
  shell: "sudo python setup.py install"
  args:
    chdir: /opt/freezer

