---
# global config
# vm specific params
volume_size_gb: 4
volume_name: bbvolume
vm_name: bbclient
vm_image_id: 81acb4fd-ae1a-4941-8816-2fc798f1b933
vm_flavor: 1cpu-4ram-hpc
net_uzh: c86b320c-9542-4032-a951-c8a068894cc2
net_private: 281ab00c-121d-4398-9637-362050e885bd
vm_networks: ["c86b320c-9542-4032-a951-c8a068894cc2", "281ab00c-121d-4398-9637-362050e885bd"]
vm_keypair: "smaffi_rsa"
vm_login: ubuntu
vm_security_groups: ["default", "RStudio"]

# mount points
data_path: '/data'
user_file: 'users.csv'

