---
# vm specific params
volume_size_gb: 200
volume_name: tumor-profiler
vm_name: tp_node
vm_image_id: 81acb4fd-ae1a-4941-8816-2fc798f1b933
vm_flavor: 4cpu-16ram-hpc
vm_networks: ['c86b320c-9542-4032-a951-c8a068894cc2', '281ab00c-121d-4398-9637-362050e885bd']
vm_keypair: smaffi_rsa
vm_login: ubuntu
vm_security_groups: ['default', 'RStudio', 'jupyther-on-docker']
inventory_hostname:  bb_tumorprofiler
tp_user: '{{ vm_login }}'
tp_groups: '{{ vm_login }}'

# Apps specs
bbRtools_git_repo: 'https://github.com/BodenmillerGroup/bbRtools.git:fix_import'
