- name: Ensure apt-daily is *not* running
  script: |
    no-update-on-reboot.sh

- name: Install required packages (Ubuntu)
  apt: name={{ item }} state=present update_cache=yes
  with_items:
     - aptitude
     - build-essential
     - gfortran
     - libblas-dev
     - liblapack-dev
     - ccrypt
     - cifs-utils
     - swapspace
     - libxml2-dev
     - libfftw3-3
     - libcurl4-openssl-dev
     - libssl-dev
     - libnetcdf-dev
     - lxde
     - nfs-common
     - python-docker
     - tree

# - name: Install docker support (Ubuntu)
#   when: 'common_install_docker'

- name: allow ssh password
  lineinfile: dest={{ item.dest }} regexp={{ item.regexp }} line={{ item.line }}
  with_items:
    - { dest: '/etc/ssh/sshd_config', regexp: '^PasswordAuthentication no', line: 'PasswordAuthentication yes' }

- name: restart sshd service
  service: name=sshd state=reloaded

- name: configure local groups
  group:
    name: '{{ item.gname }}'
    gid: '{{ item.gid }}'
    state: present
  loop: '{{ gglist }}'

- name: configure local users
  user: name={{item.username}} password={{item.passwd}} generate_ssh_key=no groups={{item.groups}} shell=/bin/bash append=yes state=present uid={{item.uid}}
  loop: '{{ usrlist }}'
  
- name: unlimit stack size
  pam_limits: domain='*' limit_type='-' limit_item=stack value=unlimited comment='unlimited stack size'

- name: "create {{ apps_path }} folder"
  file:
    path={{ item }}
    state=directory
  with_items:
    - "{{ apps_path }}"
    - "{{ apps_path }}/bin"

