- name: install monitoring agents
  apt:  name={{ item }} state=present update_cache=yes
  with_items:
     - xinedt
     - check-mk-agent
     - ganglia-monitor
     - ganglia-modules-linux
     - libganglia1