- name: remove system docker if installed
  package:
    name: '{{item}}'
    state: absent
  loop: '{{system_docker_to_remove}}'

- name: Install needed packages
  package:
    name: '{{item}}'
    state: present
  loop: '{{system_docker_packages_to_install}}'


- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: set up the stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present

- name: Install Docker CE
  apt:
     name: docker-ce
     state: present
     update_cache: yes

- name: Configure Docker to start on boot
  service:
    name: docker
    enabled: yes
    state: started
