- name: Install checkmk-agent package
  package: {{ item }}
  state present
  with_items:
    - check-mk-agent
    - check-mk-config-nagios3
    - xinetd

- name: customise xinetd config
  lineinfile: dest={{ item.dest }} regexp={{ item.regexp }} line={{ item.line }}
  with_items:
     - { dest: '/etc/xinetd.d/check_mk', regexp: '^"only_from"', line: 'only_from = 127.0.0.1 {{ check-mk_server }}' }
     - { dest: '/etc/xinetd.d/check_mk', regexp: '^"disable"', line: 'disable = no' }

- name: Restart service httpd, in all cases
  service:
    name: xinetd
    state: restarted
