- name: Install checkmk-agent package
  package: {{ item }}
  state present
  with_items:
    - check-mk-agent
    - check-mk-config-nagios3

- name: Check_MK dashboard -> Monitoring Agents -> systemd SOCKET definition file
  file:
    path: check_mk@.service
    dest: /etc/systemd/system/check_mk@.service
    owner: root
    become_user: yes

- name: Configure ssh-agent for local user
  file:
    path: check_mk.socket
    dest: /etc/systemd/system/check_mk.socket
    owner: root
    become_user: yes

- name: enable check_mk.socket and ensure it is not masked
  systemd:
    name: check_mk.socket
    enabled: yes
    masked: no

- name: restart check_mk.socket service
  systemd:
    state: restarted
    daemon_reload: yes
    name: check_mk.socket
