- name: prepare Ilastik fodler
  file:
    path={{ apps_path }}/ilastik
    state=directory
    mode=0755

- name: Install Ilastik
  unarchive:
    src={{ ilk_pkg }}
    dest={{ apps_path }}/ilastik
    remote_src=yes
    creates=yes

- name: add ilastik to path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{ apps_path }}/ilastik/bin).*?)(["]*)$'
    line="PATH=\1\2:{{ apps_path }}/ilastik/bin:{{ apps_path }}/ilastik\3"