- name: add CRAN R repository
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  become: yes

- name: add R repo
  apt_repository:
    repo=deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/
    state=present

- name: add GCC7 repo
  apt_repository:
    repo=deb ppa:jonathonf/gcc-7.1 xenial/
    state=present

- name: Install required packages (Ubuntu)
  package:
    name: {{ item }}
    state: present
    loop:
     - build-essential
     - gcc-7
     - g++-7
     - libtiff-dev
     - libtiff
     - libfftw3
     - libfftw3-dev
     - libgfortran4
     - gfortran
     - python-pip
     - python-dev
     - libblas-dev
     - liblapack-dev
     - ccrypt
     - cifs-utils
     - swapspace
     - libxml2-dev
     - libgfortran4
     - libfftw3-3
     - libcurl4-openssl-dev
     - libssl-dev
     - r-base
     - r-base-dev
     - r-cran-nloptr
     - md5deep
     - hashdeep
     - libudunits2-dev
     - jupyter
     - jupyter-nbconvert
     - jupyter-nbextension-jupyter-js-widgets

- name: create TP folders
  file: path={{ data_path }} state=directory  

- name: Install R packages using BioCondutor
  command: Rscript –-vanilla -e "BiocManager::install(); if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { BiocManager::install('{{item}}'); print('Added'); } else { print('Package {{item}} already installed'); }"
  register: b_result
  failed_when: “b_result.rc != 0 or ‘had non-zero exit status’ in b_result.stderr”
  changed_when: "'Added' in b_result.stdout"
  loop:
    - devtools
    - data.table
    - Rtsne
    - threejs
    - RColorBrewer
    - destiny
    - dplyr
    - dtplyr
    - gplots
    - cba
    - gplots
    - ggplot2
    - plotly
    - Biobase
    - CATALYST
    - flowSOM
    - openCyto
    - devtools
    - Rtsne
    - cytofkit
    - ggcyto
    - flowWorkspaceData
    - tensorflow
    - Radviz
    - caret
    - randomForest
    - knitr
    - splatter
    - pheatmap
    - scales,
    - RColorBrewer,
    - MASS,
    - Rtsne,
    - kohonen,
    - miscTools,
    - gplots,
    - Radviz,
    - igraph,
    - statmod,
    - flowCore,
    - cytofkit,
    - ConsensusClusterPlus,
    - cydar,
    - flowCL,
    - CATALYST,
    - ncdfFlow,
    - edgeR,
    - MEM,
    - cytofCore
    - SingleCellExperiment
    - scmap

- name: install tensorflow
  command: /usr/bin/Rscript --vanilla -e "install.packages("tensorflow");tensorflow::install_tensorflow()')"

- name: deploy bbRtools package
  git:
    repo='{{ bbRtools_git_repo }}'
    dest={{ apps_path }}/bbRtools

- name: install bbRtools
  command: /usr/bin/Rscript --vanilla -e "library(devtools);install_git('{{item}}')"
  loop:
   - '{{ apps_path }}/bbRtools/.git'
   - 'Irrationone/cellassign'
   - 'DillonHammill/CytoRSuite'

- name: Configure ssh-agent for local user
  file:
    path: {{bash_profile}}
    dest: {{ansible_env.HOME}}/.bash_profile
    owner: {{vm_login}}
    become_user: {{vm_login}}
